### ISSUE TITLE
[BUG] hud not appearing in 5e v1.2

### ISSUE THREAD

**Issue by MrPotatoZed** [Larkinabout/fvtt-token-action-hud-core#55] opened 2023-02-11 01:41 UTC
Upon opening foundry or refreshing the browser I get an error message indicating: 
![image](https://user-images.githubusercontent.com/85974617/218231772-153a04ab-7fa0-4052-a726-ddc44c2f03d5.png)

The hud is not appearing for any tokens; presumably as a result of the version conflict. 

**Versions:**
- Token Action HUD Core: [1.2.1; issue also present with 1.2.0]
- Token Action HUD System: [5e 1.2.0]
- System: dnd5e 2.1.4
- Foundry chrome and firefox]
-hosted on the forge

**Comment by Larkinabout** [comment] 2023-02-11 02:23
Yeah, I messed up the release somehow. Uninstall Token Action HUD D&D 5e and reinstall with this link instead: [https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/download/1.2.0/module.json](https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/download/1.2.0/module.json)

**Comment by MrPotatoZed** [comment] 2023-02-11 02:53
Yup, that's working; thanks for the quick fix.

**Comment by Malritch** [comment] 2023-02-11 03:58
It did work! I am seeing some odd behavior in the spells column with duplication. 

![spell issue](https://user-images.githubusercontent.com/125106431/218238025-54a0fa24-31a7-4f1e-ab85-853e4d425208.JPG)

**Comment by Malritch** [comment] 2023-02-11 05:23
Having some similar issues in the inventory tab as well.

**Comment by Larkinabout** [comment] 2023-02-11 07:42
What other modules are you running?

**Comment by maxphoenix01** [comment] 2023-02-11 22:06
The token action hud core and 5e modules don't show up in my module list. I'm getting the same error as OP. I tried reinstalling with the link but its the same issue.


> Upon opening foundry or refreshing the browser I get an error message indicating: ![image](https://user-images.githubusercontent.com/85974617/218231772-153a04ab-7fa0-4052-a726-ddc44c2f03d5.png)
> 
> The hud is not appearing for any tokens; presumably as a result of the version conflict.
> 
> **Versions:**
> 
> * Token Action HUD Core: [1.2.1; issue also present with 1.2.0]
> * Token Action HUD System: [5e 1.2.0]
> * System: dnd5e 2.1.4
> * Foundry chrome and firefox]
>   -hosted on the forge



> Yeah, I messed up the release somehow. Uninstall Token Action HUD D&D 5e and reinstall with this link instead: https://github.com/Larkinabout/fvtt-token-action-hud-dnd5e/releases/download/1.2.0/module.json

**Comment by Larkinabout** [comment] 2023-02-11 22:33
It's most likely the Token Action HUD D&D 5e module that is stuck on the previous version, even though it says it is updated to 1.2.0. Did you completely uninstall and then reinstall?

I'll maybe try releasing another copy to see if that fixes things as there's no issue with the latest version if it actually manages to install it.

**Comment by maxphoenix01** [comment] 2023-02-11 22:48
I did completely uninstall and reinstall using the link you provided but its the same issue. But, the link downloads the mod from the bazaar so if the module is stuck in the previous version then the same issue will keep occurring. Maybe a reupload will work.

**Comment by Larkinabout** [comment] 2023-02-11 23:17
I've released Token Action HUD D&D 5e 1.2.0 as 1.2.1. Try that. If it doesn't work, I'm probably all out of ideas!

**Comment by MrPotatoZed** [comment] 2023-02-12 02:51
In re the behavior noted by Malritch I was seeing it intermittently last night after the 1.2.0 fix, not at all this morning in some testing, but tonight I'm consistently seeing it on one token only. When I saw it last night clicking another token and clicking back cleared up action doubling but tonight it's been consistent, but only with one token. Tested with only TAH and TAH 5e active. Here's the error I'm seeing today:
![image](https://user-images.githubusercontent.com/85974617/218289901-512e2afc-defc-49df-bebd-9459dca52262.png)
I was seeing this yesterday and this morning:
![image](https://user-images.githubusercontent.com/85974617/218289904-8ff4ef8d-d208-4d98-8010-f0946ffb9bd8.png)
 Here's specifically what I'm seeing: 
![image](https://user-images.githubusercontent.com/85974617/218289916-53a0cc73-5f31-4501-acd6-ecb66fc90ffb.png)
Here's the actor: [fvtt-Actor-testy-b-(copy).txt](https://github.com/Larkinabout/fvtt-token-action-hud-core/files/10715159/fvtt-Actor-testy-b-.copy.txt)

Note this isn't a serious issue in my case as it's only a testing token that I've layered all manner of weird stuff on that shows it consistently. Just wanted to make the report in case this helps isolate what's happening.

**Comment by Larkinabout** [comment] 2023-02-12 03:05
That is useful, thanks. I'll try to reproduce it on my end.

**Comment by Malritch** [comment] 2023-02-13 14:01
I also ran Find the  Culprit to the same result. I have disabled both Core & 5e Versions.
Downloaded and enabled just Token Action Hud. 
That loads correctly.

**Comment by bearsy1** [comment] 2023-03-14 00:05
To piggy back on this thread, I too am not able to see the token action hud when I click on tokens, but the error I'm getting seems to be different than the others here. Below is my particular situation. Hope this helps!

**Foundry** 10.291
**DnD5e** 2.1.5
**Vivaldi web browser** 5.7.2921.63 (Stable channel) (64-bit) 
**Forge hosted**

**Modules loaded**
![image](https://user-images.githubusercontent.com/88817619/224858468-7d3c231f-d334-422c-a7ed-0d697dd684e3.png)

Error (only getting this one error)
![image](https://user-images.githubusercontent.com/88817619/224858605-0e9e7641-c914-4a60-9940-502984a8d9e1.png)

**Comment by Larkinabout** [comment] 2023-04-06 15:38
Fixed in Token Action HUD Core 1.3.0.

**Closed by Larkinabout** 2023-04-06 15:38 UTC
Labels: bug
