### ISSUE TITLE
[FEATURE] Everyday Heroes support

### ISSUE THREAD

**Issue by MadBlue2112** [Larkinabout/fvtt-token-action-hud-core#253] opened 2024-06-27 23:38 UTC
**Describe your idea**
Add support for [Everyday Heroes](https://github.com/evilgeniusgaming/everyday-heroes/wiki/Installation). 

I know this was requested over a year ago, but I thought that there may be more interest now that the game has been out a while. It's similar to DnD5E (although I don't know what the architecture of the Foundry system for it is like).

**Comment by Larkinabout** [comment] 2024-07-04 10:11
Closing this as a duplicate of #91.

If you haven't already, I'd suggest asking around where people are talking about Everyday Heroes for Foundry VTT to see if there's a developer willing to develop a TAH module for the system.

**Closed by Larkinabout** 2024-07-04 10:11 UTC
Labels: enhancement
