### ISSUE TITLE
[BUG] Players unable to see HUD but Gamemaster can

### ISSUE THREAD

**Issue by Singularity-error** [Larkinabout/fvtt-token-action-hud-core#70] opened 2023-02-24 03:18 UTC
When a player selects their token they own, they are unable to see the token HUD. Deleting the old profile and making a new one makes the HUD appear when the token is assigned to the new profile. After a few hours on the new profile, changing anything about the profile (such as renaming it), logging back out to the Forge homepage, or by adding actions to the linked character sheet the HUD disappears. The Gamemaster is still able to see all HUDs of the tokens even after they disappear from the player.
![troubleshooting gm working](https://user-images.githubusercontent.com/126219230/221082074-f82fc775-b8e3-4036-9bed-daf9a35f5f4d.png)
![troubleshooting broken](https://user-images.githubusercontent.com/126219230/221082109-73dd5e77-f1c6-4663-8fa6-2825a7ff9c7b.png)
![working after new profile was made from player](https://user-images.githubusercontent.com/126219230/221082226-43c22beb-b647-49ed-addd-3cb0b4b5edb6.jpg)

When the HUD disappears the only thing that fixes it is a new profile, resetting the settings under Token Action HUD core does nothing and neither does having the player reconnect to the Forge server. The entire time the gamemaster is still able to see all the players' HUDs when selecting their token and see any changes the player made to their character sheet reflected in the HUD.

- Token Action HUD Core: 1.2.3
- Token Action HUD System: token-action-hud-Pathfinder 2 0.1.1
- System: PF2E 4.8.0
- Foundry VTT: 10.291
- Browser: Google Chrome 110.0.5481.104

**Comment by Larkinabout** [comment] 2023-02-24 13:19
Hi @Singularity-error, to help investigate, please do the following steps:

1. Log on as the player.
2. Enable the 'Enable Debugging' module setting under Token Action HUD Core.
3. Reload the page (F5).
4. Open the browser console (F12).
5. Filter the console output for 'Token Action HUD'
6. Export the contents of the console output to file and attach it here.

**Comment by Singularity-error** [comment] 2023-02-24 14:25
The readout from the console that is spaced apart from the rest is the only error that was recorded.

2 foundry.js:610 Foundry VTT | Registered callback for tokenActionHudSystemReady hook
foundry.js:6771 Foundry VTT | Loaded localization file https://assets.forge-vtt.com/bazaar/modules/token-action-hud-core/1.2.3/languages/en.json
foundry.js:6771 Foundry VTT | Loaded localization file https://assets.forge-vtt.com/bazaar/modules/token-action-hud-pf2e/0.1.1/languages/en.json
2 foundry.js:610 Foundry VTT | Registered callback for tokenActionHudCoreReady hook
token-action-hud-core.min.js:1 Token Action HUD Debug | Available roll handlers Object
token-action-hud-core.min.js:1 Token Action HUD Debug | Available roll handlers Object
foundry.js:610 Foundry VTT | Registered callback for renderTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for forceUpdateTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for renderTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for forceUpdateTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for renderTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for forceUpdateTokenActionHud hook
VM988 token-action-hud-core.min.js:1 Token Action HUD Debug | Updating hud... Objecttrigger: {type: 'hook', name: 'canvasReady'}[[Prototype]]: Object
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/category.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/subcategory.hbs


VM988 token-action-hud-core.min.js:1 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'buildActionList')
[Detected 1 package: token-action-hud-core]
    at TokenActionHud._updateHud (token-action-hud-core.min.js:1:27517)


foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/action.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tagdialog.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/category.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/subcategory.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/action.hbs
foundry.js:6887 Foundry VTT | Retrieved and compiled template modules/token-action-hud-core/templates/tagdialog.hbs
token-action-hud-core.min.js:1 Token Action HUD Debug | Retrieved saved categories Object
token-action-hud-core.min.js:1 Token Action HUD Debug | Adding pre-roll handler CompendiumMacroPreHandler
foundry.js:610 Foundry VTT | Registered callback for renderTokenActionHud hook
foundry.js:610 Foundry VTT | Registered callback for forceUpdateTokenActionHud hook
VM988 token-action-hud-core.min.js:1 Token Action HUD Debug | Flags set, do not update hud {actor: CharacterPF2e, data: {…}}
VM988 token-action-hud-core.min.js:1 Token Action HUD Debug | Flags set, do not update hud {actor: CharacterPF2e, data: {…}}
VM988 token-action-hud-core.min.js:1 Token Action HUD Debug | Flags set, do not update hud {actor: CharacterPF2e, data: {…}}
VM988 token-action-hud-core.min.js:1 Token Action HUD Debug | Flags set, do not update hud {actor: CharacterPF2e, data: {…}}

**Comment by Larkinabout** [comment] 2023-02-24 16:32
Can you open up the browser console once again please and screenshot where the two modules are installed. It should be located under the 'Sources' tab and then the 'Page' tab on the left side, like this:
![image](https://user-images.githubusercontent.com/105953297/221233963-6d045c23-4f0f-4ca0-a7f0-8403f271ac13.png)

**Comment by Singularity-error** [comment] 2023-02-24 17:16
![console no token hud](https://user-images.githubusercontent.com/126219230/221242106-ab601cb8-9636-408e-b320-2997ad3d088d.png)
After searching through the pages, I did not find the Token HUD (core or PF2E) listed anywhere on the player side or on the GM side when I looked through the console there. They were both activated on the "Manage Modules" and were downloaded from the Bazar for Forge.

Currently attempting to uninstall from the Bazar and reinstalling while in the client (as you would for premium modules).
When I downloaded them from the Client, I got compatibility warnings about Token HUD Core and PF2E not being listed to work with ver.10.291 of Foundry.
After the reinstall, the module is still missing from the pages, and the GM is still the only one who can view the HUD.
![console client reinstall still missing](https://user-images.githubusercontent.com/126219230/221244431-80247069-609a-4469-beff-88df41f4c6fb.png)

**Comment by Larkinabout** [comment] 2023-02-24 18:49
I think The Forge may be accessing them directly from the bazaar rather than installing them into the modules folder. In the posted console log, it shows that the languages folder is being accessed from:  
https://assets.forge-vtt.com/bazaar/modules/token-action-hud-core/1.2.3/ – if that's true for the entire module, then the TAH Pathfinder 2 module is likely not able to locate the TAH Core module's files.

Can you try installing them using the direct links from the Foundry VTT site and uncheck the box that tells the Forge to install them from the bazaar? If that works, it'll tell me what I need to do to avoid issues with the bazaar.

**Comment by Singularity-error** [comment] 2023-02-24 19:17
![installation proof](https://user-images.githubusercontent.com/126219230/221270958-6864584d-2c00-42bf-8081-23dad1cb79fb.png)
![IT WORKS](https://user-images.githubusercontent.com/126219230/221270970-f528e95b-a7d0-478d-9360-d2f510f3e50b.png)
It appears that the problem was with the Bazar installation, as this time I downloaded from the manifest links from Foundry and they both appear under modules in the console and the players can see the HUD now. Hopefully, they don't disappear again like the create a new player solution.

**Comment by Aragith** [comment] 2023-02-25 18:12
I'm experiencing the same issue when using The Forge. Not sure if it helps, but I created a fresh world with just the following modules installed:
![image](https://user-images.githubusercontent.com/124524014/221372427-b20b834d-73e3-413a-b7de-0257edecdf9f.png)

Sources/Pages tab from console when logged in as "GM logged in as Player":
![image](https://user-images.githubusercontent.com/124524014/221372533-3c0c4514-c40d-48a2-8888-951d69619c97.png)

Then farther down:
![image](https://user-images.githubusercontent.com/124524014/221372596-96db17b2-160b-4301-abf4-1d5b2e484786.png)

In between is just a bunch more of those random string asset files.

And here is the error that appears on the console for the token actor when logged in as "GM logged in as Player":
![image](https://user-images.githubusercontent.com/124524014/221372330-9723797f-cd6e-4cdf-80e2-fc43e96c6608.png)

I had noticed the error during my prep for my new campaign starting this coming week and was trying to troubleshoot it. Glad I'm not the only one having the issue. I thought it may have just been me and a corrupt world again like the Shortsword issue, but hopefully it can get resolved.

Everything works fine when logged in as the GM and interacting with tokens - the token action hud works as intended and expected. This error/issue only occurs when logged in as a player. I am on the same system, on the same account, and the same browser. Something is happening when a player tries to access the module.

Hope this helps!

**Comment by Larkinabout** [comment] 2023-02-25 18:45
Hi @Aragith, until this is fixed, I would do the same as @Singularity-error and install the modules manually rather than using the bazaar. This will install them into your modules folder rather than referencing them from the bazaar.

**Comment by Aragith** [comment] 2023-02-25 21:43
Hi @Larkinabout, I will definitely do that and use the manifest. I just wanted to give you more information in case it was useful in your debugging.

Thanks again for the awesome module and the work you do!

**Comment by cgplayer2000** [comment] 2023-03-02 19:45
@Larkinabout and @Singularity-error, I appreciate all the discussion about this issue.  I too have this issue (on Forge), and just noticed it as I was testing things getting ready for a session this weekend.  I would have spent hours troubleshooting this.

**Comment by Larkinabout** [comment] 2023-04-06 15:42
Fixed in Token Action HUD Core 1.3.0.

**Closed by Larkinabout** 2023-04-06 15:42 UTC
Labels: bug
